language: python
python:
  - '2.7'
  - '3.4'
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c 'CREATE DATABASE "gigaware";' -U postgres
  - python manage.py db upgrade
script: coverage run manage.py test
after_success:
  - coveralls
